# Generated by Django 4.2.21 on 2025-05-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendTranslation',
        ),
        migrations.DeleteModel(
            name='VersionHistory',
        ),
    ]
