# Generated by Django 4.2.21 on 2025-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('attorney', 'Attorney'), ('client', 'Client')], default='attorney', max_length=50, verbose_name='Role'),
        ),
    ]
